#!/bin/bash

# Setup logging stdout + stderr to logfile
log_file="/var/log/postinstall.log"

function log_handler {
  while IFS='' read -r output; do
    echo $output
    echo "$(date) - $output" >> $log_file
  done
}

exec &> >(log_handler)

adduser --disabled-password --gecos "" jump
echo "jump:moutarde" | chpasswd
cat <<EOF >/home/jump/.openrc
export OS_AUTH_URL=https://auth.cloud.ovh.net/v2.0/
export OS_TENANT_ID=TODO
export OS_TENANT_NAME=TODO
export OS_USERNAME=TODO
export OS_PASSWORD=TODO
export OS_REGION_NAME="DE1"
EOF
echo '. ~/.openrc' >> /home/jump/.bashrc

apt update
apt -y dist-upgrade
apt -y install vim git python-dev python-setuptools build-essential curl
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
pip install --upgrade pip setuptools wheel virtualenv
pip install python-openstackclient ansible 2>&1 || true
apt -y purge cloud-init
